os: linux
dist: trusty
sudo: required

language: go
go:
- "1.12"

branches:
  only:
  - development
  - master

before_script:
- env GO111MODULE=on go get -v github.com/gohugoio/hugo
script:
- hugo

addons:
  apt:
    update: true

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  target_branch: master
  local_dir: public
  on:
    branch: development
